// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MineTimbermanBot.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MineTimbermanBot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805135319_DeleteLastWorkTime")]
    partial class DeleteLastWorkTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MineTimbermanBot.Application.Duels.Duel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("ChallengerChoice")
                        .HasColumnType("integer");

                    b.Property<bool>("ChallengerChoiceAuto")
                        .HasColumnType("boolean");

                    b.Property<int?>("ChallengerDmMessageId")
                        .HasColumnType("integer");

                    b.Property<string>("ChallengerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ChallengerUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("OpponentChoice")
                        .HasColumnType("integer");

                    b.Property<bool>("OpponentChoiceAuto")
                        .HasColumnType("boolean");

                    b.Property<int?>("OpponentDmMessageId")
                        .HasColumnType("integer");

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("OpponentUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("StatusMessageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChallengerUserId");

                    b.HasIndex("OpponentUserId");

                    b.ToTable("Duels", (string)null);
                });

            modelBuilder.Entity("MineTimbermanBot.Application.Sessions.UserSession", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("BoltsInWorkSession")
                        .HasColumnType("integer");

                    b.Property<string>("CharacterName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Force")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastRestTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LogsInWorkSession")
                        .HasColumnType("integer");

                    b.Property<int>("Lucky")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("MineTimbermanBot.Infrastructure.Persistence.Entities.ChatMembership", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ChatId", "UserId");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMemberships", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
