// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MineTimbermanBot.Infrastructure.Persistence;

#nullable disable

namespace MineTimbermanBot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MineTimbermanBot.Application.Duels.Duel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChallengerChoice")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChallengerChoiceAuto")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChallengerDmMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChallengerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("ChallengerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OpponentChoice")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OpponentChoiceAuto")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OpponentDmMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("OpponentUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusMessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChallengerUserId");

                    b.HasIndex("OpponentUserId");

                    b.ToTable("Duels", (string)null);
                });

            modelBuilder.Entity("MineTimbermanBot.Application.Sessions.UserSession", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoltsInWorkSession")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Force")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastRestTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastWorkTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("LogsInWorkSession")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedSide")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("MineTimbermanBot.Infrastructure.Persistence.Entities.ChatMembership", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatId", "UserId");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMemberships", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
